- python/cli/prelude_cli/cli.py
- python/sdk/prelude_sdk/models/account.py
Re: https://github.com/preludeorg/libraries/issues/128
Fixes scenario 1 (`existing keychain file (nothing overrides)`)
> fix cli configure

- javascript/sdk/.env.test
- javascript/sdk/lib/controllers/iam.ts
- javascript/sdk/test/e2e/iam.spec.ts
This PR adds the e2e tests for the IAM routes in the javascript SDK. It blocks #152
> test: add e2e test for iam

- javascript/sdk/lib/controllers/detect.ts
- javascript/sdk/test/e2e/detect.spec.ts
This PR adds the e2e tests for the Detect routes in the javascript SDK. It blocks #152
> test: add e2e test for detect

- shell/probe/demo.ps1
I was getting the following error:
` Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel. `
SO on this error: by default powershell uses TLS 1.0 the site security requires TLS 1.2
> windows 10 fix

- shell/probe/install.ps1
Raindrop expects an environment variable that contains the token
> Set token in env

- shell/probe/demo.ps1
- shell/probe/install.ps1
- shell/probe/raindrop.ps1
solves this error: `The request was aborted: Could not create SSL/TLS secure channel.`
By default powershell uses TLS 1.0 and looks like we require TLS 1.2
> specify TLS protocol

- shell/probe/demo.ps1
- shell/probe/raindrop.ps1
PR wraps our VST invocation in a try/catch to catch when the file fails to run b/c Defender prevents it
`ApplicationFailedException` is thrown when Defender prevents the test from running - I'm not sure if this exception is also thrown for other reasons though. There's no good documentation on what throws this. If we want to be certain, we could do string parsing of the exception message, but there's always a risk to error message changes IMO
Example of output with this code:
>  handling windows defender in demo & raindrop

- go/probe/internal/hades/hades.go
- python/probe/presto.py
- shell/probe/demo.sh
- shell/probe/nocturnal.sh
Bringing other probes up-to-date with recent windows changes:
* return test outcome only, not `max(test,clean)`
* update demo to account for other potential exit codes
> updates probes (return test result always, have demo handle exit codes better)

- python/cli/prelude_cli/views/detect.py
problem: create-endpoint currently defaulting to empty tag
```
{
"endpoint_id": "drip",
"tags": [
""
],
"updated": "2023-01-24 15:44:12.461269"
},
```
> default no tags

- python/sdk/prelude_sdk/models/codes.py
we `create-user` with the lowest permission by default, which relies on our permissions list being ordered
`default=[p.name for p in Permission][-1]`'
moving UNKNOWN to the top of the list so that SERVICE is the "lowest" permission
> move UNKNOWN to not be last

- .github/actions/hades/action.yml
- .github/actions/moonlight/action.yml
- .github/actions/presto/action.yml
- .github/actions/shell_probes/action.yml
When a step fails in a job, the job stops running in github actions. This means we were not notified for deploy failures. This pr makes sure the notification still comes out (it will say deploy failed)
> Always post status to slack

- python/cli/prelude_cli/views/detect.py
YYYY-MM-DD will parse to the zeroth hour of that day so we don't get that day's results if we strip to that
> pass full timestamp

- shell/probe/install.sh
Fixes the following error by running as system
> Run with the right domain-target

- python/cli/prelude_cli/views/interactive.py
corner case where the long term solution is to not allow a tag that is an empty string and to delete any current tags that are empty string. but this is a bandaid in the meantime for the corner case
> dont die on empty string tag

- javascript/sdk/lib/types.ts
Might need this for a ticket I'm pushing up. This just matches the fact that there's an edr_id in ProbeActivity with string | null. Happy to hear your objections.
> Matching edr_id type on ProbeActivity

- javascript/sdk/lib/controllers/detect.ts
- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
Per mahina and Francis, the BE will populate these fields for us thus leaving it to be optional.
> remove start and finish on describeActivity

- python/cli/prelude_cli/views/interactive.py
The field we display in GetAccount is still called 'control' (not 'partner'), so I'm leaving that wording in interactive still. This PR just keeps interactive functional after https://github.com/preludeorg/libraries/pull/515
> swap control to partner: interactive

- python/cli/prelude_cli/views/interactive.py
- python/cli/setup.cfg
fixes: https://github.com/preludeorg/libraries/issues/458
* the `readline` import holds the magic that allows line editing (ex. cursor moves back a char instead of typing `^[[A`)
* `Prompt.ask()` was a little funky with `readline` so moved to normal `input`
> fix: have python parse arrow keys/etc correctly

- python/cli/setup.cfg
per pypi: "It has been renamed to GNUREADLINE to resolve a name clash with the standard library module. "
> gnureadline not readline

- python/cli/prelude_cli/views/interactive.py
* Remove large-data views (logs, probes) entirely -> summary views (days, rules) are only ones remaining
* Remove filtering on days view
* Limit days logs to last 2 weeks
* Limit to showing 10 insights
* Fix rules view (wasn't working) and only show rules that have results
* Add menu option in "View Results" to take you to the executive dashboard
> interactive: slim down results options

- python/sdk/prelude_sdk/controllers/partner_controller.py
error:
```
def deploy(self, partner_name: str, host_ids: list[str]):
TypeError: 'type' object is not subscriptable
```
> py-sdk fix: dont type the list

- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
the backend is returning the DayResult object like this so I am updating the JS SDK unless we want to fix the BE instead. Here is a PR to provide an option
> fix DayResult Typing

- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
This PR reverts back the typing of the day objects date key to date time to match what the BE is sending.
> Update day object typing: date to datetime

- javascript/sdk/lib/controllers/detect.ts
- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
This PR adds the listAdvisories function for the JS SDK and returns a newly created Advisory object. As well, this PR updates the nomenclature for the applicable objects that were being used in "units" which are now "advisories"
> feat: listAdvisories and typing in JS SDK

- javascript/sdk/test/sdk.test.ts
upload might not have length 1 if compute uploads the compiled binaries fast enough
> make js sdk UploadTest test more robust

- shell/demo/demo.ps1
re: https://detectors.atlassian.net/browse/DET-374
I believe the issue is that the installer sets PRELUDE_DIR and also restricts access to it. So if you run the installer and then run demo after that, you (the normal user) wont have access to PRELUDE_DIR anymore
If we need to keep letting users override the `.vst` dir for demo runs, we can also change the name of the env variable to `PRELUDE_DEMO_DIR` or something
> hardcode PRELUDE_DIR

- javascript/sdk/package.json
Necessary for NPM JS publish and the reason is based on the removal of published param for createTest and removal of it from Test object
> bump SDK version for new createTest changes

- javascript/sdk/test/sdk.test.ts
- python/sdk/tests/templates/template.go
- python/sdk/tests/test_build_controller.py
- python/sdk/tests/test_detect_controller.py
> all tests are passing except there are still inconsistencies with the probe timing out before both tests can run and describe-activity tests pass 100% of the time. I have seen it pass before on both python and JS today so I would consider it fine just inconsistent.
Update to this ^ @makk94 helped me debug, thank you!, but a solution to the issue that we were facing is that we were not giving compute enough time to handle the test attachments, so adding a 5s sleep did the trick.
> Updating python and JS sdk tests

- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
This PR adds the 3 new response values from the metrics view and also adds a missing response value of account_id for the Account object which I found was not being handled properly yesterday ( I didn't know we added that to the response). @makk94 can you double check all these inclusions with BE code please.
> add new metric responses

- .github/CODEOWNERS
Github wasn't properly assigned reviewers, I think it had to do with the extra `*`
> fix codeowners file

- javascript/sdk/test/sdk.test.ts
prior to this, we were resolving the probe test after we got two completions of tests, but now that was not resolving as the created empty test is marked irrelevant and skipped so a change in test structure was made. This matches what we have in the python sdk test better.
> matching probe test with python

- python/cli/prelude_cli/views/build.py
This PR:
- Provides `hidden=True` to hide advisory flag from help blurb when creating tests
- Reorders params in definition so that the advisory parameter comes last, being hidden and all
> fix(cli): Hide advisory flag from help blurb when creating a test

- python/cli/prelude_cli/views/build.py
NOTE: This PR is awaiting changes for the Python SDK.
This PR:
- updates the CLI to accept an optional `--techniques` or `-q` flag which accepts comma-separated values corresponding to valid MITRE ATT&CK technique codes.
- additionally adds a hidden attribute to the advisory flag for update-test, which was missed while doing #694 
```
❯ prelude build create-test ... --techniques T1557
❯ prelude build create-test ... -q T1557
❯ prelude build create-test ... --techniques T1557,T1040
❯ prelude build create-test ... -q T1557,T1040
```
```
❯ prelude build update-test ... --techniques T1003
❯ prelude build update-test ... -q T1003
❯ prelude build update-test ... --techniques T1003,T1539
❯ prelude build update-test ... -q T1003,T1539
```
```
❯ prelude build create-test --help
Usage: cli.py build …
```
> feat(cli) - Add techniques flag to create-test and update-test

- javascript/sdk/lib/types.ts
Sneaking this in before 1.2.13 sdk update
> remove Prelude permission type to match Python

- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
This PR matches the JS Exit codes with the python sdk and also does a version bump for release
> update JS Exit Codes and Version 1.3.0 bump

- javascript/sdk/package.json
This is needed for new publish to include 110 exit code
> bump JS SDK to 1.3.1 for new 110 exit code

- javascript/sdk/lib/controllers/partner.ts
- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
- python/sdk/prelude_sdk/controllers/partner_controller.py
This PR updates the /partner endpoints to take in a `partner-code` which is an enum value. For example `endpoint/deploy/1`
Thoughts on naming convention @makk94 ? Not sure if I should switch between partner and control
> Update partner endpoints to use new control codes

- javascript/sdk/package.json
This is needed to update the exit codes. I forgot to include it in my other PR
> JS version bump to 1.3.4

- javascript/sdk/lib/controllers/build.ts
- javascript/sdk/lib/controllers/detect.ts
- javascript/sdk/lib/controllers/iam.ts
- javascript/sdk/lib/controllers/partner.ts
- javascript/sdk/lib/controllers/probe.ts
- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
- javascript/sdk/test/sdk.test.ts
- python/sdk/prelude_sdk/controllers/detect_controller.py
- python/sdk/prelude_sdk/controllers/partner_controller.py
- python/sdk/setup.cfg
This PR updates the responses of multiple endpoints (primarily for JS SDK as we comply with types) following the responses listed [here](https://preludeorg.slack.com/docs/T7GV7S3B4/F05JXGQ2W3C). To recap some changes:
- Adding the test attachments to the test object that gets returned from getTest, createTest, and updateTest
- Update multiple endpoints, primarily those related to deletes, to return a {status:true} response 
- Return the attachment on upload-attachment
- Add type for AuditLog and update endpoint to return that type
- Smaller updates of minor significance on other endpoints and small refactors of code
- Updated tests to work with new responses
Checklist:
> update endpoint responses for JS and Python

- javascript/sdk/lib/types.ts
- python/sdk/prelude_sdk/models/codes.py
This PR removes the weekly and monthly run code options. No version bump required as it was handled in https://github.com/preludeorg/libraries/pull/731/
> remove weekly and monthly runcodes

- javascript/sdk/package.json
This is needed to publish new JS sdk to include exit code changes
> JS Version Bump 1.3.7 (exit code changes)

- python/cli/prelude_cli/views/detect.py
- python/sdk/prelude_sdk/controllers/detect_controller.py
Example: create endpoint:
```
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile qa-us2 detect create-endpoint -h m -s k -t det550 --partner DEFENDER              
cbfd290ba20de2afb0d168917a646702
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile qa-us2 detect endpoints
[
{
"endpoint_id": "17f85c1f-7675-4d2b-bb92-66d8e236cd8e",
"host": "m",
"serial_num": "k",
"edr_id": null,
"control": 2,
"tags": [
"det550"
],
"last_beacon": "2023-08-01",
"created": "2023-08-01 23:00:53.785782"
},
```
Example: update control to None:
```
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile qa-us2 detect update-endpoint 17f85c1f-7675-4d2b-bb92-66d8e236cd8e --partner None
{
"id": "17f85c1f-7675-4d2b-bb92-66d8e236cd8e"
}
(venv) …
```
> [det550] update register/update endpoint with control

- javascript/sdk/lib/types.ts
- python/sdk/prelude_sdk/models/codes.py
Reason: 137 means some other process stopped the probe. This would either be a defensive control or, if on a container, the OS indicating that there is not sufficient memory to finish the test. In either case, the endpoint would be protected.
> Swapping exit code to correct value

- javascript/sdk/lib/controllers/detect.ts
- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
- python/sdk/prelude_sdk/controllers/detect_controller.py
- python/sdk/tests/test_detect_controller.py
I want to double check that that id in the registerEndpoint is correct. Not sure if the extra `:` was needed to be kept at the end
> remove control & EDR ID from update/register endpoint

- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
Are there any other updates made to the backend recently that I should be aware of to include in this update pr?
> fix: update last_beacon to last_seen and remove debug runcode

- shell/probe/nocturnal.sh
- shell/probe/raindrop.ps1
- Make PRELUDE_DIR not configurable
- Remove print statement
- Split curl into 2 calls
> Chore: use the test ID as the filename when writing to disk

- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
This PR adds the dos property to the probe object and assigns the type Platform to it, for reference Platform is:
export type Platform =
| "darwin-arm64"
| "darwin-x86_64"
| "linux-x86_64"
| "linux-arm64"
| "windows-x86_64"
| "windows-arm64"
| "unknown";
@kenrick for your awareness
> chore: add dos to probe object

- shell/probe/raindrop.ps1
Dat being set to $null causes an event log error of 
```
Object reference not set to an instance of an object.
```
This also means a probe does not run tests for a second time. 
Setting Dat to an empty string (like is done at the begining of the script) fixes that behavior and the probe will check in correctly.
> chore: bug fix for probe not checking in

- javascript/sdk/lib/controllers/iam.ts
- javascript/sdk/package.json
- javascript/sdk/test/sdk.test.ts
This test will not pass until we adjust the response on the BE to be `{status: true}` instead of the currently `{Status:true}` which is not aligned to how other endpoints respond.
> fix: verify User URL & add resetPassword test

- javascript/sdk/lib/controllers/detect.ts
- javascript/sdk/lib/controllers/iam.ts
- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
- javascript/sdk/test/sdk.test.ts
- python/sdk/tests/test_detect_controller.py
- python/sdk/tests/test_iam_controller.py
This PR updates the typing for the JS DescribeActivity to remove the `tests` view and update the `social` and `day` responses.
social returns:
`{
account: { unprotected: number; volume: number };
social: { unprotected: number; volume: number };
}`
and day returns: 
`{
unprotected: number;
volume: string;
}`
This PR also fixes the sdk tests to account for accounts being on autopilot mode by default
> chore: update activity views and fix tests (JS SDK 1.4.9)

- go/tests/endpoint/endpoint.go
Adding some wiggle room to compensate for Windows Defender. There are instances where Defender's quarantine process causes tests to hit timeout. Tested with 20 seconds on my end and can no longer recreate the issue.
> Increase endpoint timeout to 20 seconds

- javascript/sdk/lib/controllers/detect.ts
- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
- javascript/sdk/test/sdk.test.ts
This PR does the following:
- Remove tags from "insights", "probes", and "logs" views
- Add impersonate to the query
- Remove deprecated "observed" property from "logs"
- Remove null from control for endpoints and "probes" view responses
- Add null option for dos on endpoints response
> update activity types and remove tags

- javascript/sdk/lib/controllers/detect.ts
- javascript/sdk/lib/types.ts
- javascript/sdk/package.json
- javascript/sdk/test/sdk.test.ts
- python/sdk/tests/test_detect_controller.py
Adds new power and default views. Adds powerActivity typing for the power view response. In that response, we say that policy, version, dos, and control are all optional properties and may not be returned from the BE
Adjusts for better checks on tests
> add power and default views (JS SDK 1.4.14)

- go/tests/endpoint/endpoint.go
This PR adds a collections of constants which reflect the error codes defined in the [Detect docs](https://docs.preludesecurity.com/docs/understanding-results) and use descriptive names. Merging this would allow us to create tests like this:
```go
func test() {
Endpoint.Say("Extracting file for quarantine test")
Endpoint.Say("Pausing for 3 seconds to gauge defensive reaction") 
if Endpoint.Quarantined("SharpWMI.exe", malicious) {
Endpoint.Say("Malicious file was caught!")
Endpoint.Stop(Endpoint.FileQuarantinedOnExtraction)
return
}
Endpoint.Say("Malicious file was not caught")
Endpoint.Say("Executing SharpWMI")
randomIndex := rand.Intn(len(commands))
command := commands[randomIndex]
_, err := Endpoint.Shell(command)
if err != nil {
Endpoint.Say("Execution was prevented") …
```
> Feature: Add constants for results

- python/cli/prelude_cli/templates/template.go
This is a simple upgrade to the template used when creating a new test that will make use of the new logging function.
> Replace println() with Endpoint.Say() in Go test template

- go/tests/endpoint/endpoint.go
Missed these when I removed the PortScan struct.
> Remove unnessary imports from Endpoint.

- python/cli/prelude_cli/views/detect.py
- python/cli/prelude_cli/views/iam.py
- python/cli/prelude_cli/views/partner.py
- python/sdk/prelude_sdk/controllers/detect_controller.py
- python/sdk/prelude_sdk/controllers/iam_controller.py
- python/sdk/prelude_sdk/controllers/partner_controller.py
- python/sdk/prelude_sdk/models/codes.py
* have sdk take enum params instead of ints
* sdk then sends string names instead of ints to API
* **Added EnumMeta to our codes:** By default a non-existent enum string  will throw a KeyError. The EnumMeta `__getitem__` will catch that error and redirect to the normal enum constructor.
* so anything using ints will continue to work (backwards compatible woo) (ex. `RunCode[2]` is `RunCode.WEEKLY`)
* and non-existent string will  fall through to the `__missing__` method (ex. `RunCode['mahinas-birthday']` will be `RunCode.DAILY`)
with https://github.com/preludeorg/service/pull/1448
> det-772 [a]: pass enum strings to API

- python/sdk/prelude_sdk/models/codes.py
since path variables are strings in BE
> fix: try to convert to int in MissingItem EnumMeta

- python/sdk/prelude_sdk/models/codes.py
so we can track if we're missing any common exit codes
> chore: log unknown exitcodes

- go/tests/endpoint/endpoint.go
An increasing number of our tests rely on the following pattern to execute a randomly selected command on each test execution.
```go
func check() {
commands := [][]string{
{"cmd.exe", "/C", "foo.exe bar"},
{"cmd.exe", "/C", "c:\Windows\System32\bar.exe 123"},
{ "powershell.exe", "-c", "Get-Foobar" },
}
index := rand.Intn(len(commands))
command := commands[randomIndex]
Endpoint.Shell(command)
}
```
This is a valuable feature of our tests as it lets us extend a give test to exercise multiple variations of the same operation. To reduce code reuse and standardize our implementation (no more `math/rand` vs `crypto/rand`), this new Endpoint function abstracts command selection away from the developer and leverages the exists, tested `Shell` function to execute the randomly chosen command.
> Adding random command selection function to Endpoint

- python/cli/prelude_cli/views/detect.py
About the only issue I could see here, would be if we started supported directories in tests. But I really don't want to think about that right now, and this is a demonstrated problem on an existing us2 test. Also, if we ever want to push 0fe330f2-7a9c-48c0-a268-5600b4a15ea7 to us1, we won't get that file.
> DET-832: remove guard so we download files without suffixes

- javascript/sdk/test/sdk.test.ts
- javascript/sdk/test/templates/template.go
- python/cli/prelude_cli/templates/README.md
- python/cli/prelude_cli/templates/template.go
- python/cli/prelude_cli/views/build.py
Added functionality to the cli's `build` feature that writes a templated `README.md` markdown file (also included in this update) to the new test's directory when a user creates a new test with `prelude build create-test <opts>`.
Currently, this functionality is broken up for readability, but can be condensed if need be, for example by combining both file writes into one `with open` call. I think it should probably remain separated, though.
Sample cli output screens:
> Template README On Test Creation

- go/tests/endpoint/endpoint.go
In this PR:
- Added the `Wait()` function to `endpoint.go`. This function when called pauses the test for time `dur`. If `dur` is passed as <= 0, `Wait()` pauses for 3 seconds (as a hack default value). Else it pauses for `dur` seconds.
- Added timestamp functionality to `Say()`. Now, a timestamp is prepended to each and every logged message. The goal of this change is to enable customers to easily cross-reference event/activity times observed in their SIEM with those pronounced by the test, providing valuable information usable in solution tuning, test activity attribution, etc.
-- Before: 
-- After: 
-- The timestamp format is currently set to the same format seen on the test start-stop messages. This is for consistency.
- Moved the const var decls to the top of the source code body.
> Added Wait() function. Added timestamping to Say(). Housekeeping.

- go/tests/endpoint/endpoint.go
In this PR:
- Changed `Endpoint.pwd()` into an exported function, `Endpoint.Pwd()`. This provides syntax sugar and convenience to VSTs that need to interact with the file system (like with embedded payloads being written to disk) without needing to import/reimport `os`, `syscall`, etc.
> Updated Endpoint.pwd() into an exported function

- shell/probe/nocturnal.sh
- shell/probe/raindrop.ps1
Also, fix upgrade path for raindrop :( 
If when this goes in, I'll update probe_tasks probe version as well to trigger upgrades (for nocturnal anyway)
PR bundle:
- https://github.com/preludeorg/backbone/pull/719
- https://github.com/preludeorg/service/pull/1601
- https://github.com/preludeorg/libraries/pull/934
> det-975: get probe sleep interval from BE

- .github/actions/shell_probes/action.yml
The notifcations were using `GITHUB_REF` which is not valid (cf. https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables).
They should use `github.ref`.
> fix: [DET-1022] Fix probe deploy notifcations.

- go/tests/endpoint/endpoint.go
Lots of feelings about this. Ultimately though it should just be removed.
> Remove IsSecure() from Endpoint.go

- go/tests/endpoint/endpoint.go
In this PR:
Modified the `XorEncrypt` and `XorDecrypt` functions in Endpoint.go to utilize different encoding logic over a longer key, more closely resembling something observable ITW. 
This produces data output which is slightly less trivial for endpoint security appliances/solutions to decode, making the tests which employ this functionality that much more difficult and therefore useful & impactful.
> Slightly more robust xor functionality

- python/sdk/tests/test_build.py
- python/sdk/tests/test_detect.py
- python/sdk/tests/test_iam.py
- python/sdk/tests/test_partner.py
- python/sdk/tests/test_probe.py
* move to `schedule/unschedule` instead of `enable/disableTest`
* add Get/ListThreats tests - using a predetermined prelude test might get flakey, but we'll see how it plays out and adjust if necessary
* add one threat in schedule when testing probe
> det-1120: add Threats API sdk tests

- python/sdk/tests/test_probe.py
I think I'd just written this expectation before I decided to create a new endpoint just for the probe (so the 7 was including tests that ran earlier in the test suite on different endpoint)
> fix: fix python sdk test_describe_activity

- python/sdk/tests/test_build.py
- python/sdk/tests/test_iam.py
* test purging a test
* fix existing test tombstone test
* fix expected probe sleep time in iam test
I didn't add a test for deleting/purging a threat because everything in the SDK threats appears to be done as a regular user test and threats can only be created / deleted by the prelude account. Looks like there are no create threat tests in there already and I assumed that is why. If that assumption is incorrect let me know and I'll see about adding some tests around threats.
> det-1130: add test for purging a test

- python/sdk/tests/test_build.py
- python/sdk/tests/test_probe.py
these tests rely on real prelude tests in us2 - things are achangin; this PR catches the tests up to speed
> fix python sdk tests

- go/tests/endpoint/endpoint.go
This MR adds a new helper function that checks to make sure that the test runs on a supported operating system. Currently, we're only supporting Windows, macOS, and Linux.
> Add GetOS helper function to Endpoint

- python/cli/prelude_cli/views/detect.py
- python/cli/setup.cfg
The CLI printout of the sigma rule shows a sigma rule detection like 
```
"ParentImage": [
".*\\s+Hi\\\\\\\\cmd.exe"
]
```
b/c printing a dictionary apparently calls `_repr_` not `_str_`
Writing the detection to a file will show the strings correctly (`.*\s+Hi\\\\cmd.exe`) and also, a yaml file is how you call Create and UpdateDetection, so it makes that flow easier too
> det-1491: add --output_file flag to GetDetection CLI

- python/sdk/prelude_sdk/models/codes.py
In error cases, we get empty string exit codes, so this is just to avoid the uncaught exception of
```
TypeError: %d format: a real number is required, not str
```
> cleanup: log missing Exitcode as string

- shell/probe/nocturnal.sh
`[[` is a bashism, and ubuntu defaults to dash. 
Debian has a "checkbashism" script, that you can install via brew, which would have called this out. 
```
checkbashisms libraries/shell/probe/nocturnal.sh 
possible bashism in libraries/shell/probe/nocturnal.sh line 28 (alternative test command ([[ foo ]] should be [ foo ])):
if [[ $code -ne 102 ]]; then
```
> DET-1602: dash compatibility

- shell/probe/nocturnal.sh
- shell/probe/raindrop.ps1
My fix was incomplete. $code can resolve to nothing, which will never work with a -ne in test. Wrapping it in quotes and comparing with a string comparison seems like a suitable change. 
```
root@i-021078d13f7ac91d8:~# if [ $code -ne 102 ]; then echo no; fi
-bash: [: -ne: unary operator expected
root@i-021078d13f7ac91d8:~# if [ "$code" -ne 102 ]; then echo no; fi
-bash: [: : integer expression expected
root@i-021078d13f7ac91d8:~# if [ "$code" -ne "102" ]; then echo no; fi
-bash: [: : integer expression expected
root@i-021078d13f7ac91d8:~# if [ "$code" != "102" ]; then echo no; fi
no
root@i-021078d13f7ac91d8:~# if [ "102" != "102" ]; then echo no; fi
```
> DET-1602: Update if statement

- go/tests/endpoint/endpoint.go
In this PR:
- we implement a dropper execution flow to be used in conjunction with VSTs which write malicious files to disk at time-of-test. this dropper is employed as a sacrificial child process of the vst process. it is implemented because we observed AV/EDR interdicting at time-of-test on those tests which write to the FS by killing the vst process, which would short-circuit the vst's code path, preventing them from emitting the proper exit code -- for example, instead of exiting PROTECTED::FileQuarantinedOnExtraction (int 127), we would instead see exit codes like (int -1). the execution model we adopt with this dropper program is such that the AV/EDR interdiction will target the dropper and not the vst process, allowing for the vst to emit the proper exit code and thus preserve test …
> Endpoint Library IPC Functionality

- go/tests/dropper/dropper_darwin.go
- go/tests/dropper/dropper_linux.go
- go/tests/dropper/dropper_windows.go
- go/tests/dropper/go.mod
In this PR:
- we implement a new module, `Dropper`
-- this module demonstrates a flexible, multi-platform approach to embedding a file dropper (to be used with the Endpoint package's `Dropper()` function)
-- to use in a test, the test must import this module. then, the byte slice `Dropper.Dropper` represents the executable binary's bytes that are written to the testing directory at time-of-test for file socket IPC payload handling
an example of implementing this in a VST follows:
```
...
import (
Dropper "github.com/preludeorg/libraries/go/tests/dropper"
Endpoint "github.com/preludeorg/libraries/go/tests/endpoint"
)
...
func test() {
if err := Endpoint.Dropper(Dropper.Dropper); err != nil {
Endpoint.Say("%v", err)
Endpoint.Stop(Endpoint.UnexpectedTestError)
}
... proceed with the rest of …
```
> Added embeddable dropper module sources

- python/cli/prelude_cli/views/build.py
- python/cli/prelude_cli/views/detect.py
- python/sdk/prelude_sdk/controllers/build_controller.py
- python/sdk/prelude_sdk/controllers/detect_controller.py
```
(venv) mahinakaholokula@Mahinas-MacBook-Pro-2 libraries % prelude build undelete-threat e523ddac-825a-4f62-9ad5-303521bdb638
Threat could not be undeleted. Check that the tests it contains are not tombstoned.
(venv) mahinakaholokula@Mahinas-MacBook-Pro-2 libraries % prelude build undelete-test 550f9bfd-d077-48dc-8ed1-cecff5afcbc7  
{
"status": true
}
(venv) mahinakaholokula@Mahinas-MacBook-Pro-2 libraries % prelude build undelete-threat e523ddac-825a-4f62-9ad5-303521bdb638
{
"status": true
}
(venv) mahinakaholokula@Mahinas-MacBook-Pro-2 libraries % prelude detect techniques
...
{
"id": "T1659",
"name": "Content Injection",
"description": "Adversaries may gain access and continuously communicate with victims by injecting malicious content into systems through online network traffic. …
```
> add Undelete and ListTechnique APIs to CLI

- .github/workflows/release.yml
Took a couple commits, but we got there. 
This run fails: https://github.com/preludeorg/libraries/actions/runs/10746017831/job/29806176774 but it's because we've already shipped the 2.0 sdk to pypi. With an appropriate semver, it would have gone thru. 
I can't test it until the first real run, but I'm pretty sure this will also tag the repo right.
> DET-1220: fix invalid-publisher #1

- python/cli/prelude_cli/views/build.py
- python/sdk/tests/conftest.py
- python/sdk/tests/test_build.py
- python/sdk/tests/test_detect.py
- python/sdk/tests/test_partner.py
* update API responses
* add new tests (Defender ODP)
* fix small CLI bug (update-test was erroring if control wasn't being updated)
us2 run:
```
===================================================================================== short test summary info =====================================================================================
FAILED python/sdk/tests/test_partner.py::TestPartner::test_observed_detected[defender] - assert 1 <= 0
+  where 0 = len([])
FAILED python/sdk/tests/test_generate.py::TestGenerate::test_generate_from_partner_advisory - Exception: ('Failed to get advisory %s: %s', 10241168, [{'message': 'PDF is not found.  Please validate parameter(s) in your query'}])
====================================================================== 2 failed, 94 passed, 12 skipped …
```
> fix up py sdk tests

- python/cli/prelude_cli/views/build.py
- python/cli/prelude_cli/views/shared.py
The `rglob(...)` function will return files recursively, but this includes subdirectories. The `upload(...)` function will attempt to open those directories and throw an exception. Specifically `[Errno 21] Is a directory`. So I've added a check to `upload(...)` to return immediately if passed a directory. Additionally, I've modified the error message that is returned to include all of `e.args` because `e.args[0]` was `21` and `e.args[1]` was `Is a directory`, which is more useful for debugging purposes.
> Fixed random 21 error when uploading subdirectories

- python/sdk/prelude_sdk/models/account.py
- raise a better error when account/handle/hq isn't in the keychain profile
- raise an error when custom oidc doesn't have slug (this shouldn't happen unless someone messes with their configured keychain file directly)
> Det 2739: account must be in keychain
