preludeorg/libraries

python/cli/prelude_cli/templates/template.c
python/cli/prelude_cli/templates/template.cs
python/cli/prelude_cli/templates/template.swift
python/cli/prelude_cli/views/build.py
python/sdk/prelude_sdk/controllers/build_controller.py

1. Swapping create_ttp column name to question
2. Updating the create-code-file path
3. Adding comments to code file templates
4. Adding deploy url command

Swapping name to question

---

javascript/sdk/lib/controllers/build.ts
javascript/sdk/package.json

Small bug with getting code files

Fix get code file

---

javascript/sdk/lib/controllers/build.ts
javascript/sdk/package.json

deleteTTP was calling the wrong route

Fix delete ttp in js sdk

---

python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py
python/sdk/prelude_sdk/models/account.py

Closes https://github.com/preludeorg/libraries/issues/19

Create missing config file

---

python/cli/prelude_cli/views/detect.py

Closes https://github.com/preludeorg/libraries/issues/44

Map question id to name

---

python/sdk/prelude_sdk/models/account.py

Closes https://github.com/preludeorg/libraries/issues/79
Closes https://github.com/preludeorg/libraries/issues/77

Merge keychain on configure

---

python/cli/prelude_cli/views/build.py

Closes https://github.com/preludeorg/libraries/issues/78

Add windows as a supported platform

---

python/cli/prelude_cli/views/iam.py
python/cli/prelude_cli/views/shared.py

Closes https://github.com/preludeorg/libraries/issues/95

Prompt to overwrite profile with iam create-account

---

python/cli/prelude_cli/cli.py
python/cli/prelude_cli/views/build.py

without this, help looks like this:
```
Commands:
clone            Clone all variants to your local environment
create-test      Create or update a test
create-variant   Create a new test variant
delete-test      Delete TEST TEST is the UUID of a security test
delete-variant   Delete VARIANT
delete-verified  Delete Verified test NAME is the name of a verified test
get-test         List all variants for TEST TEST is the UUID of a
security...
list-tests       List all tests
list-verified    List all verified tests
purge            Delete all tests and variants
run              Compile and validate VARIANT
save             Upload the variant at PATH to your Prelude database
url              Generate a download URL for VARIANT VARIANT is the name...
```

dont wrap newline

---

go/probe/cmd/hades/hades.go
go/probe/internal/hades/hades.go
python/cli/prelude_cli/cli.py

Re: https://github.com/preludeorg/libraries/issues/98

align go probe w/ other probes

---

python/sdk/prelude_sdk/models/account.py

Re: https://github.com/preludeorg/libraries/issues/128, scenario 2

fix cli configure

---

javascript/sdk/index.html
javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/controllers/iam.ts
javascript/sdk/package.json

This PR aims to sync the changes on the python SDK to the javascript SDK

Add lists probes and purge account to JS SDK

---

python/cli/prelude_cli/views/detect.py

on top of https://github.com/preludeorg/service/pull/373

return full report not just failures

---

shell/install/install.sh

re: https://github.com/preludeorg/libraries/issues/126

dont write to file if probe download fails

---

javascript/sdk/lib/client.ts
python/sdk/prelude_sdk/models/account.py

Reverts preludeorg/libraries#137

Revert "send sdk version in header"

---

javascript/sdk/lib/client.ts
javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/controllers/iam.ts
javascript/sdk/lib/service.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

This PR fixes and update the tests for the detect controller

fix: detect controller methods and types

---

javascript/sdk/lib/controllers/iam.ts
python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py

This PR adds the update-handle cmd to the python cli

add update handle cmd to cli

---

.gitignore
python/cli/setup.cfg
python/sdk/setup.cfg

- bump cli / sdk versions
- SDK / CLI release

sdk cli version bumps

---

powershell/probe/raindrop.ps1

Note: tested on an x86_64, haven't run on arm

powershell probe

---

javascript/sdk/lib/controllers/build.ts
javascript/sdk/test/e2e/build.spec.ts
javascript/sdk/vite.config.ts

This PR adds the e2e tests for the Build routes in the javascript SDK.  It blocks #152

test: add e2e tests for build

---

shell/probe/demo.sh

@privateducky I added some spacing here and there and proposing use of checkmarks in the terminal? This way we have status for what's in progress [*], completed [✓] and [!] alerts

Updated spacing

---

shell/install/install.sh

fixes https://github.com/preludeorg/libraries/issues/165

create parent directories

---

javascript/sdk/package.json

This PR bumps the JS SDK version to 0.9.15

bump js sdk version

---

javascript/sdk/lib/controllers/build.ts
python/cli/prelude_cli/views/build.py
python/sdk/prelude_sdk/controllers/build_controller.py

@kenrick i did a small change in the js sdk and couldn't ctrl F where the thing was used in Build... not sure if it is being used but I feel like it should be ....

rename name to filename

---

javascript/sdk/lib/controllers/build.ts
javascript/sdk/package.json

This PR changes name to id in the computeProxy request

fix: change name to id

---

shell/probe/demo.ps1
shell/probe/demo.sh

updated bash demo:
- updated wording & coloring per https://github.com/preludeorg/roadmap/issues/46#issuecomment-1375786732
- better error handling (print response code & exit early)
- sending max of (testresult, cleanresult) when saving results
bash demo tested on darwin m1
ps demo tested on windows 11

update bash demo & add powershell

---

shell/probe/install.ps1
shell/probe/install.sh

re: https://github.com/preludeorg/libraries/issues/191

make endpoint name a param

---

shell/probe/demo.ps1
shell/probe/demo.sh

per: https://github.com/preludeorg/roadmap/issues/46#issuecomment-1378284797

update wording of installation question and move to end

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/package.json

This PR fixes list probes in the JS SDK

fix list probes

---

shell/probe/demo.ps1
shell/probe/install.ps1
shell/probe/raindrop.ps1

fixes https://github.com/preludeorg/libraries/issues/212
Was able to repro the problem on a  Windows_Server-2016-English-Core-Base-2023.01.11 vm and confirm the fix on it

-UseBasicParsing in web requests

---

shell/probe/install.ps1

Fix launch of scheduled tasks

---

python/cli/prelude_cli/views/detect.py
python/sdk/prelude_sdk/models/codes.py

re: some of https://github.com/preludeorg/libraries/issues/226

cli updates: show enable_test default, show runcode as name not int

---

swift/probe/Sources/moonlight.swift

forgot that moonlight existed... catching it up

return test code from moonlight

---

javascript/sdk/lib/controllers/build.ts
javascript/sdk/package.json

Update download/update to use attachment routes in JS SDK

---

python/cli/prelude_cli/views/detect.py

re: https://github.com/preludeorg/libraries/issues/226
```
(venv) mahinakaholokula@Mahinas-MacBook-Pro cli % prelude detect list-queue
[
{
"test": "39de298a-911d-4a3b-aed4-1e8281010a9a",
"run_code": "DAILY",
"tag": null,
"rule": "Health check"
}
]
```

add rule name to list-queue

---

shell/probe/README.md
shell/probe/demo.ps1
shell/probe/install.ps1
shell/probe/raindrop.ps1

Getting an env var in powershell can be done multiple ways

Environment variable consistency

---

shell/probe/demo.ps1
shell/probe/install.ps1
shell/probe/raindrop.ps1

tested on windows2019: ami-0c4af4610ab22c4f4

return if isnt a thing (at least on my VM)

---

.github/workflows/install-prod.yml

#240 had the wrong variables set for the prod deploy

Prod deploy using the wrong variables

---

shell/probe/demo.ps1
shell/probe/demo.sh

re: https://github.com/preludeorg/libraries/issues/221

remove install from demo

---

javascript/sdk/lib/controllers/build.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

Update SDK types to remove attachments from test

---

.github/actions/moonlight/action.yml
.github/workflows/moonlight-prod.yml
.github/workflows/moonlight-staging.yml

Moonlight Build / Deploy

---

.github/actions/presto/action.yml
.github/workflows/presto-prod.yml
.github/workflows/presto-staging.yml

Initial presto

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

Add 'observe' API route to JS-SDK

---

shell/probe/demo.ps1
shell/probe/demo.sh

re: https://github.com/preludeorg/test/issues/48#issuecomment-1403632054

demo: dont clean up if test blocked

---

shell/probe/raindrop.ps1

Closes https://github.com/preludeorg/test/issues/44

raindrop - handle unauthorized write 

---

shell/probe/install.sh

Fixes https://github.com/preludeorg/libraries/issues/274

Use bootout/bootstrap instead of unload/load

---

javascript/sdk/index.html
javascript/sdk/lib/controllers/build.ts
javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

Update JS SDK to match Pythons

---

javascript/sdk/index.html
javascript/sdk/lib/controllers/build.ts
javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

Update JS SDK to match Python SDK

---

javascript/sdk/index.html
javascript/sdk/lib/client.ts
javascript/sdk/lib/service.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

This PR adds a request inceptor to allow users to change parts of the requests before its sent. Eg. Changing the _product based on which env the sdk it running in.

add request interceptor

---

shell/probe/install.ps1
shell/probe/install.sh

re: https://github.com/preludeorg/libraries/issues/239
Our backend currently only accepts a list, not a comma-separated list - if you're waiting for that update, it's coming, just lmk here!

add endpoint tag option on install

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

Add insights to js sdk

---

python/cli/prelude_cli/views/detect.py

re: https://github.com/preludeorg/build/issues/506

show DELETED in activity for deleted tests

---

python/cli/prelude_cli/views/detect.py
python/sdk/prelude_sdk/controllers/detect_controller.py

re https://github.com/preludeorg/service/issues/579
dependent on https://github.com/preludeorg/service/pull/588
no changes needed in js sdk

comma-separated tags on enable-test

---

javascript/sdk/index.html
javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

Fixes https://github.com/preludeorg/build/issues/501

Add activity view query params

---

javascript/sdk/index.html
javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/controllers/iam.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

Closes: https://github.com/preludeorg/build/issues/570

Add get account route to iam

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

this PR adds the js sdk for the recommendations api based on :

feat: update js sdk for recommendations api

---

python/cli/prelude_cli/views/detect.py

Reverts preludeorg/libraries#354

Revert "update days view"

---

python/cli/prelude_cli/views/build.py
python/cli/prelude_cli/views/detect.py
python/cli/prelude_cli/views/iam.py

in the CLI, we only offer a --days flag, and I think most folks would suspect that covers from beginning of the first day to end of "today" (rather than literally X days ago to the second)

update all timestamps in CLI

---

python/cli/prelude_cli/cli.py
python/cli/prelude_cli/views/build.py
python/cli/prelude_cli/views/detect.py
python/cli/prelude_cli/views/iam.py
python/cli/prelude_cli/views/interactive.py
python/sdk/prelude_sdk/controllers/build_controller.py
python/sdk/prelude_sdk/controllers/detect_controller.py
python/sdk/prelude_sdk/controllers/probe_controller.py

What you'll find here:
- A new interactive CLI wizard, which can be engaged via ``prelude interactive``
- ``build tests`` has moved to ``detect tests``
- ``build url`` and ``build compute`` have been removed

New interactive wizard mode

---

javascript/sdk/index.html
javascript/sdk/lib/controllers/build.ts
javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

This PR syncs the JS SDK with python

Sync JS SDK

---

python/cli/prelude_cli/views/interactive.py

View schedule with None tags

---

python/cli/prelude_cli/views/interactive.py

Add menu titles to top section

---

python/cli/prelude_cli/views/interactive.py

Fix for when you choose 1 tag and no sensitivity level

Deploy probe fix when no sensitivity level selected

---

python/cli/prelude_cli/views/interactive.py

add test id to upload menu

---

python/cli/prelude_cli/views/detect.py

re:https://github.com/preludeorg/libraries/issues/407
This is the output without anything special. Do we want to convert to Enum names?

fix social-stats

---

shell/demo/demo3.ps1
shell/demo/demo3.sh

Pinged @preludeorg/wizards (Harry) for verbiage review.

Adding demo3

---

python/cli/prelude_cli/views/detect.py
python/sdk/prelude_sdk/controllers/detect_controller.py

 add --days flag to list_endpoints

---

shell/demo/demo4.ps1
shell/demo/demo4.sh

Pending test ID which I should have from the team today.
EDIT: Test id's added. Pinged @preludeorg/wizards and let Harry know it was ready for review.

Adding demo4

---

python/cli/prelude_cli/views/build.py
python/sdk/prelude_sdk/controllers/build_controller.py

Re: https://detectors.atlassian.net/browse/DET-45
relies on https://github.com/preludeorg/service/pull/686
Testing (personal stack). Created a new test and uploaded some files to it. Also downloaded all  of them back to local to confirm text is correct/ executables run. Here's my s3 of what was tested:

upload as binary files

---

javascript/sdk/package.json

Needed to do this for the last change.

Upgrade version

---

shell/demo/demo5.ps1
shell/demo/demo5.sh

Pinged Harry to let him know this is ready for his review.

Adding demo5

---

python/sdk/prelude_sdk/controllers/build_controller.py

fixes: https://github.com/preludeorg/libraries/issues/447
tested:
```
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile hat build create-test GLASS
Created 69ee36ff-fc98-4b96-8207-4992ff30356c.go
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile hat build download 69ee36ff-fc98-4b96-8207-4992ff30356c  
Downloading 69ee36ff-fc98-4b96-8207-4992ff30356c
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % cat 69ee36ff-fc98-4b96-8207-4992ff30356c/69ee36ff-fc98-4b96-8207-4992ff30356c.go
/*
ID: 69ee36ff-fc98-4b96-8207-4992ff30356c
NAME: GLASS
CREATED: 2023-03-15 20:16:58.829306
*/
package main
import (
"github.com/preludeorg/test/endpoint"
)
func test() {
Endpoint.Stop(100)
}
func clean() {
Endpoint.Stop(100)
}
func main() { …
```

fix parenthesis on headers [upload attachment]

---

shell/probe/nocturnal.sh

We have restart on failure in our mac/linux installers

exit 1 on bad CA

---

.github/actions/hades/action.yml
.github/actions/moonlight/action.yml
.github/actions/shell_probes/action.yml

- bucket variable, and post action status not job status
- err

fix probe deployment

---

.github/actions/shell_probes/action.yml
.github/workflows/shell_probes-prod.yml
.github/workflows/shell_probes-staging.yml

Fix for pushing updated probes to the wrong location, and updated workflow names since the install scripts are gone.

Broaden the sed. Put nocturnal in the right place

---

python/cli/prelude_cli/views/iam.py
python/cli/prelude_cli/views/interactive.py

```
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile qa --interactive    
package main                                                                                              
// This is a Verified Security Test                                                                       
import (                                                                                                  
Endpoint "github.com/preludeorg/test/endpoint"                                                        
)                                                                                                         
func test() {                                                                                             
Endpoint.Stop(100) …
```

spelling fixes, email handle in interactive

---

python/sdk/prelude_sdk/models/codes.py
python/sdk/tests/test_iam_controller.py

remove autopilot from libraries

---

python/cli/prelude_cli/views/interactive.py

Depends on https://github.com/preludeorg/platform/pull/870
Closes https://detectors.atlassian.net/browse/DET-100

feat: interactive open dashboard with credentials

---

python/cli/prelude_cli/views/interactive.py

* Rename "control" or "integration" to "partner" everywhere
* Fix ListPartners and DetatchPartner (wasn't working)

interactive: fix and rename partner stuff

---

python/cli/prelude_cli/views/interactive.py

* add legend to recommendations table view
* add click through of recommendation that shows full description (often too long to fit in summary table) and latest decision
* add option to approve/deny the recommendation after click-thru

interactive: expand recommendations section

---

python/cli/prelude_cli/views/interactive.py

* Renaming to better english
* add DEBUG option to run codes
* dedupe tests in DescheduleTest function (used to have dupes because we were from the queue which is one line per unique test _and tag_)

interactive: rename and debug schedule section

---

python/cli/prelude_cli/views/interactive.py

interactive: show hostname on delete endpoint

---

python/cli/prelude_cli/views/interactive.py

The section headers just help break up the text a little and helps draw attention to when text is printed (since it prints on top of the menu)
Added nosplash env variable option for those who are using interactive more regularly and dont need/want the splashes anymore

interactive: add section headers, optional nosplash

---

python/cli/prelude_cli/cli.py

now that profiles are becoming first class citizens in the UI...

feat: add autocomplete for proflie

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/test/sdk.test.ts

update disable_test to take tags: js sdk, tests

---

python/cli/prelude_cli/cli.py

remove profile autocomplete

---

javascript/sdk/lib/controllers/iam.ts
javascript/sdk/lib/controllers/partner.ts
python/sdk/prelude_sdk/controllers/partner_controller.py

shifting route of partners API (attach/detach)

---

javascript/sdk/lib/controllers/partner.ts
python/cli/prelude_cli/views/partner.py
python/sdk/prelude_sdk/controllers/partner_controller.py

following: https://github.com/preludeorg/service/pull/844
also: update "name" to be a positional arg in endpoints and deploy (for consistency)

update paths for partner endpoints

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

This PR updates the new rule typing under the newly named `Unit` as well as makes start and finish params required for describe activity

update rule typing and params

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json
javascript/sdk/test/sdk.test.ts

This PR changes some type definitions in the activity views to reflect units instead of Rules.

fix: update types for units and tests

---

.github/workflows/shell_probes-platform-us-east-1.yml

Automation for the new platform.us-east-1.preludesecurity.com site.

automation

---

javascript/sdk/lib/types.ts
javascript/sdk/package.json

think its just a revert of https://github.com/preludeorg/libraries/commit/128dad9e51a66afe747215191a6c9f77adf25134

revert DayResult typing

---

shell/demo/demo.ps1
shell/demo/demo.sh

tested on my mac and a windows 2022 VM

update demo script (test only LockBit, update PROTECTED codes)

---

javascript/sdk/lib/types.ts
javascript/sdk/package.json

Is this all we have / need so far @makk94

add expires to User object

---

shell/probe/raindrop.ps1

Only write the message of the exception, don't write the entire stack

---

python/cli/prelude_cli/views/partner.py
python/sdk/prelude_sdk/controllers/partner_controller.py

```
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile personal partner attach crowdstrike --user 8b410b9b7106432bb1f9bb6ec22ddd10 --secret 829537w6Dtl4OHzeL1x0KMqIaGiBoPuAbJkprNZs                   
{
"base_url": "https://api.us-2.crowdstrike.com",
"authenticated": true
}
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile personal partner attach crowdstrike --user 8b410b9b7106432bb1f9bb6ec22ddd10 --secret 829537w6Dtl4OHzeL1x0KMqIaGiBoPuAbJkprNZ
{
"base_url": "https://api.crowdstrike.com",
"authenticated": false
}
```

display attach partner output

---

javascript/sdk/lib/controllers/build.ts
javascript/sdk/lib/controllers/detect.ts
javascript/sdk/package.json

@makk94 I see you updated the pathing but this PR updates where the code lives and properly moves them to the detect controller

fix: move getTest & download to detect controller

---

javascript/sdk/lib/controllers/build.ts
javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/controllers/iam.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

This PR updates the JS SDK to match the Python one as well as creates a new function call in the form of "auditLogs" which the JS SDK was missing.

updating JS SDK (1.1.12) to match Python SDK

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

JS mirror PR for https://github.com/preludeorg/libraries/pull/641

Update list advisories for JS SDK

---

python/cli/prelude_cli/views/build.py
python/sdk/prelude_sdk/controllers/build_controller.py

re: https://detectors.atlassian.net/browse/DET-152
alternative to the 4 PRs that move compute to an event trigger and upload to presigned urls

error on upload to big

---

javascript/sdk/lib/types.ts
javascript/sdk/package.json

from Mahina's comment: `i updated Get/List test response to have a test_id field instead of id`

update Test object typing

---

javascript/sdk/lib/types.ts
javascript/sdk/package.json

Reverts preludeorg/libraries#661

Revert "update Test object typing"

---

javascript/sdk/lib/client.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json
javascript/sdk/test/sdk.test.ts

This PR fixes all JS SDK tests, but I would like you approval before merge @privateducky and if we should continue to test /partner/endpoint api calls. I will say I have had no issues in my testing cycles.

fix JS SDK tests

---

.github/CODEOWNERS

This is my formal application for code ownership

Application for code ownership

---

javascript/sdk/lib/controllers/build.ts
javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

parallel JS PR for #673 
As well as adding `state` to the `endpoints` response object

WIP update JS sdk for create/update test and endpoint

---

javascript/sdk/lib/controllers/iam.ts
javascript/sdk/lib/types.ts
python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py

> Doing this blind without BE changes, so might need adjustments based on @makk94 feedback. Will keep In draft state until
Have seen Marina's comments and made changes, still a question for Mahina to answer and to review my CLI code (first time altering it and want to be sure)

adding company fields to createAccount, updateAccount, getAccount

---

javascript/sdk/test/sdk.test.ts
python/sdk/tests/test_iam_controller.py

update tests for new company field

---

javascript/sdk/lib/controllers/iam.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json
python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py

This is a follow up PR to the comments Mahina left on https://github.com/preludeorg/libraries/pull/677#pullrequestreview-1468180363
This adds consistency across SDKs and better handling of optional fields for applicable endpoints. Next time I will be better about publishing a new SDK version before I can get feedback from Mahina which I am trusting a lot as she is my connection to the backend.

consistency across SDKs

---

javascript/sdk/lib/types.ts
javascript/sdk/package.json

This PR adds the not_revelant typing to the Test and Advisories views response object

add not_relevant typing

---

python/cli/setup.cfg
python/sdk/setup.cfg

Bump python version for cli / sdk release.

bump python versions

---

javascript/sdk/lib/controllers/build.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json
javascript/sdk/test/sdk.test.ts
python/sdk/prelude_sdk/controllers/build_controller.py

adding techniques field to create/update test

---

python/sdk/prelude_sdk/controllers/build_controller.py
python/sdk/prelude_sdk/controllers/detect_controller.py
python/sdk/prelude_sdk/controllers/iam_controller.py

https://detectors.atlassian.net/browse/DET-540

fix: let nullable fields update to null

---

go/tests/endpoint/endpoint.go

This PR adds a new struct for TCP port scanning to Endpoint. This will allow us to have a standardize way to conduct single and multi-port scans.
Example multi-port usage:
```package main
import (
Endpoint "github.com/preludeorg/test/endpoint"
)
func main() {
portScanner := &Endpoint.PortScan{}
results := portScanner.ScanHosts([]int{8080, 80, 443, 5000}...)
if len(results) > 0 {
Endpoint.Stop(101)
} else {
println("No results found.")
Endpoint.Stop(100)
}
}
```

Adding portscan struct (Endpoint)

---

javascript/sdk/lib/types.ts
javascript/sdk/package.json

This PR updates the account object to include the list of controls to support multiple controls per account

updating account object to include list of controls

---

javascript/sdk/lib/types.ts
javascript/sdk/package.json

This PR is the JS parallel PR for https://github.com/preludeorg/libraries/pull/718/files

Adding control code enums to JS SDK

---

javascript/sdk/lib/types.ts
javascript/sdk/package.json

this PR updates the control type to reflect the new format of {id: number associated to a control; api: url (string) }

update control type

---

python/sdk/prelude_sdk/models/codes.py

for: https://github.com/preludeorg/service/pull/1190

[det550] add is_siem property to Control

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json
javascript/sdk/test/sdk.test.ts

parallel PR for https://github.com/preludeorg/libraries/pull/740/files

update register and update Endpoint on JS

---

python/sdk/prelude_sdk/models/codes.py

remove log on Control.__missing__

---

python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py

PR bundle:
* https://github.com/preludeorg/backbone/pull/444
* https://github.com/preludeorg/service/pull/1187
* https://github.com/preludeorg/glue/pull/51
* https://github.com/preludeorg/libraries/pull/741
```
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile personal iam create-account
Overwrite local account credentials for selected profile? [y/N]: y
Enter your email: mahina@preludesecurity.com
(Optional) Enter your name: 
(Optional) Enter your associated company: 
{
"account": "86c5c33145e3d902f1dc1b1eb45d7af7"
}
Check your email to verify your account.
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile personal iam account       
{"message":"Unauthorized"}
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile …
```

[det-564] add reset & verify user to python sdk/cli

---

python/sdk/prelude_sdk/controllers/iam_controller.py

with https://github.com/preludeorg/service/pull/1213

[DET-564] account_id instead of account

---

python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py

This reverts commit 3336fcf939c40b366b5c3d43aa5a2c464031eeb8.

Revert "[det-564] add reset & verify user to python sdk/cli (#741)"

---

python/cli/prelude_cli/views/partner.py
python/sdk/prelude_sdk/controllers/partner_controller.py

PR bundle:
- https://github.com/preludeorg/partners/pull/51
- https://github.com/preludeorg/service/pull/1219
- https://github.com/preludeorg/libraries/pull/753
- https://github.com/preludeorg/backbone/pull/470

det-605: add partner_block sdk/cli

---

javascript/sdk/lib/controllers/partner.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

This PR is a parallel js sdk pr for https://github.com/preludeorg/libraries/pull/753

adding /block to js sdk

---

javascript/sdk/lib/types.ts
javascript/sdk/package.json

parallel PR for https://github.com/preludeorg/libraries/pull/761

add sentinel one control code to js sdk

---

python/cli/prelude_cli/views/detect.py

update cli to remove edrId and Control from update/register Endpoint

---

python/sdk/prelude_sdk/models/codes.py
shell/probe/nocturnal.sh
shell/probe/raindrop.ps1

Sleep is there only for debug purposes, which I will be solving separately this week.

Chore: remove unused run code & hard code sleep

---

javascript/sdk/test/sdk.test.ts
python/sdk/tests/test_detect_controller.py

fix: update sdk tests to not include default health check and debug run code

---

shell/probe/raindrop.ps1

https://github.com/preludeorg/libraries/pull/789

Adjust raindrop to read from body

---

javascript/sdk/lib/types.ts

parallel PR for https://github.com/preludeorg/libraries/pull/784
not bumping package version since we are doing a full deployment

chore: add vectr control to JS SDK

---

javascript/sdk/lib/controllers/iam.ts
javascript/sdk/lib/types.ts
python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py

Parallel ticket for https://github.com/preludeorg/libraries/pull/799 for JS as well as minor consistency changes for python sdk

DET-564: JS SDK

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts

chore: remove advisories view and unused types

---

go/probe/debug/main.go
shell/probe/nocturnal.sh
shell/probe/raindrop.ps1

I'm told our pipeline will need an update.

Update ca to "true" location

---

javascript/sdk/lib/controllers/iam.ts
javascript/sdk/package.json
python/sdk/prelude_sdk/controllers/iam_controller.py

Please hold off on merge @privateducky until @kenrick or @khyberspache review

fix: verify-user add request_credentials

---

python/cli/prelude_cli/views/detect.py

start 29 days back, finish 1 day forward to get todays data too

fix: make detect days value default to 30

---

go/tests/endpoint/go.mod

@packplusplus has already done this for us2.

Update go to 1.21

---

shell/demo/demo.ps1
shell/demo/demo.sh

Updated links to point at the advisory page since our old public test repo has been deleted.

Update Demo links

---

python/cli/prelude_cli/views/build.py
python/sdk/prelude_sdk/controllers/build_controller.py

fix: always encode uploads

---

go/tests/network/USAGE.md
go/tests/network/go.mod
go/tests/network/network.go

As a note this will also require removal of PortScan out of Endpoint once everything has been migrated over. I'll include that change in a separate PR once tests are migrated and pushed into us2.

Adding new network package

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

- change `default` to `overview`
- add `endpoint` view and resposne
- change `version` to `os` on probeActivity response

javascript sdk 1.5.0

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

This PR changes the version to os type change in the activity query as well as change the type of number to control code for the value in the findings object

version to os, number to control code (JS SDK 1.5.3)

---

python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py

```
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile personal iam subscribe ATTACH_PARTNER CREATE_TEST UPLOAD_ATTACHMENT 
{
"email": "mahina@preludesecurity.com",
"subscriptions": [
16,
1,
2
]
}
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude --profile personal iam account --noqueue               
{
"account_id": "86c5c33145e3d902f1dc1b1eb45d7af7",
"whoami": "mahina@preludesecurity.com",
"company": "",
"mode": 0,
"controls": [
{
"id": 4,
"api": "https://usea1-partners.sentinelone.net"
},
{
"id": 1,
"api": "https://api.us-2.crowdstrike.com"
},
{
"id": 3,
"api": "https://splunk-dev.shared-dev.preludesecurity.com"
}
],
"users": [
{
"handle": "mahina@preludesecurity.com",
"permission": 0,
"name": "",
"expires": "2024-08-01 12:48:33.582483", …
```

det-772 [b]: add subscribe/unsubscribe

---

go/tests/endpoint/endpoint.go

This PR moves us to standardized XOR, AES and key generation. 
- Add XOR encryption and decryption with single-byte key.
- Implement AES encryption and decryption using GCM mode.
- Utilize math/rand for key generation.
Example usage:
**AES:**
```golang
func main() {
data := []byte("Hello World!")
fmt.Println("Original Plaintext:", string(data))
encrypted, key, err := Endpoint.AES256GCMEncrypt(data)
if err != nil {
fmt.Println("Error during encryption:", err)
return
}
fmt.Println("Encrypted Data:", encrypted)
fmt.Println("Encryption Key:", key)
decrypted, err := Endpoint.AES256GCMDecrypt(encrypted, key)
if err != nil {
fmt.Println("Error during decryption:", err)
return
}
fmt.Println("Decrypted Plaintext:", string(decrypted))
}
```
**Output:**
```bash
Original Plaintext: Hello World! …
```

Feature: Implement XOR and AES encryption/decryption (Endpoint)

---

javascript/sdk/lib/types.ts
javascript/sdk/package.json

LMK if it cant be undefined @makk94

Add policy_name (JS SDK 1.5.6)

---

javascript/sdk/lib/controllers/detect.ts
javascript/sdk/lib/types.ts
javascript/sdk/package.json

chore: remove statuses from describeActivity (JS SDK 1.5.8)

---

python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py
python/sdk/prelude_sdk/models/codes.py

PR bundle:
* https://github.com/preludeorg/service/pull/1568
* https://github.com/preludeorg/backbone/pull/701
* https://github.com/preludeorg/libraries/pull/924

det-949: add update-user to CLI and subscribable events 

---

python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py

PR bundle:
- https://github.com/preludeorg/backbone/pull/705
- https://github.com/preludeorg/service/pull/1579
- https://github.com/preludeorg/libraries/pull/927

det-950: add slug to account

---

python/sdk/prelude_sdk/models/codes.py

PR bundle:
- https://github.com/preludeorg/backbone/pull/708
- https://github.com/preludeorg/service/pull/1582
- https://github.com/preludeorg/libraries/pull/928

det-908: add RUN_ONCE runcode

---

python/cli/prelude_cli/views/build.py
python/sdk/prelude_sdk/controllers/build_controller.py

Backend updated the field: https://github.com/preludeorg/service/pull/1655

det-1066: CLI update from techniques to technique field (create/updateTest)

---

python/cli/prelude_cli/views/build.py
python/cli/prelude_cli/views/detect.py
python/sdk/prelude_sdk/controllers/build_controller.py
python/sdk/prelude_sdk/controllers/detect_controller.py
python/sdk/prelude_sdk/models/codes.py

ListThreats
```
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude detect threats
[
{
"account_id": "prelude",
"id": "101602cb-7e13-477b-a5d2-0c56fa9887c8",
"source_id": "aa24-046a",
"name": "Threat Actor Leverages Compromised Account of Former Employee to Access State Government Organization",
"source": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa24-046a",
"published": "2024-02-15",
"tests": [],
"tombstoned": null,
"created": "2024-02-15 19:11:16.712779"
},
```
GetThreat
```
{
"account_id": "prelude",
"id": "101602cb-7e13-477b-a5d2-0c56fa9887c8",
"source_id": "aa24-046a",
"name": "Threat Actor Leverages Compromised Account of Former Employee to Access State Government Organization",
"source": "https://www.cisa.gov/news-events/cybersecurity-advisories/aa24-04 …
```

det-1063: threats CLI

---

python/cli/prelude_cli/views/build.py
python/cli/prelude_cli/views/detect.py
python/sdk/prelude_sdk/controllers/build_controller.py
python/sdk/prelude_sdk/controllers/detect_controller.py
python/sdk/tests/requirements.txt
python/sdk/tests/test_build.py
python/sdk/tests/test_detect.py

* remove `advisory` field from request and response in CreateTest / UpdateTest
* remove ListAdvisories API
* remove `advisories` activity view

det-1107: removing advisories

---

python/cli/prelude_cli/views/detect.py
python/sdk/prelude_sdk/controllers/detect_controller.py

it's been replaced by schedule/unschedule commands

det-1065: remove enable/disableTest from CLI/python SDK

---

python/cli/prelude_cli/views/detect.py
python/sdk/prelude_sdk/controllers/detect_controller.py

CLI staying with single test/threat for now. lists of dicts are awkward in CLIs

det-1151: update schedule/unschedule python SDK to take a list of tests/threats

---

python/cli/prelude_cli/views/detect.py
python/sdk/prelude_sdk/controllers/detect_controller.py
python/sdk/tests/test_build.py
python/sdk/tests/test_detect.py
python/sdk/tests/test_probe.py

* alphabetize imports
* the threat I'm using in GetThreat had metadata updates
* schedule params were wrong. so was the response I was expecting
I ran them locally this time and all are passing

fix python sdk tests

---

python/cli/prelude_cli/views/partner.py
python/sdk/prelude_sdk/controllers/partner_controller.py

Ex. how block (send IOA to crwd) and reports (get reports that you made to crwd) look in CLI:
```
prelude partner block CROWDSTRIKE -t 45bb1ab8-338b-48f4-a72c-ee114eec45d3
[
{
"platform": "windows",
"status": "already_exists"
},
{
"platform": "mac",
"status": "created",
"created": "2024-03-16T00:43:32.791563714Z"
}
]
prelude partner reports CROWDSTRIKE -t 45bb1ab8-338b-48f4-a72c-ee114eec45d3
[
{
"platform": "windows",
"created": "2024-03-16 00:40:46.379666"
},
{
"platform": "mac",
"created": "2024-03-16 00:43:32.791563"
}
]
```

det-1225: CLI for IOAs pt 2 (get reports)

---

python/cli/prelude_cli/cli.py
python/cli/prelude_cli/views/build.py
python/cli/prelude_cli/views/generate.py
python/cli/prelude_cli/views/shared.py
python/sdk/prelude_sdk/controllers/build_controller.py
python/sdk/prelude_sdk/controllers/generate_controller.py

* Generate threat uploads a PDF, polls the status, and writes the output disk
* Add a directory option to create-threat to take threat intel output and create tests and a threat

Add generate threat intel

---

python/cli/prelude_cli/views/build.py
python/sdk/prelude_sdk/controllers/build_controller.py
python/sdk/tests/test_build.py
python/sdk/tests/test_iam.py

* threat sdk tests are enhanced b/c we've opened up Create/Update/Delete to non-Prelude accounts
* sadly cannot test the detection API since that is feature flagged

det-1225: enhance sdk tests for threats; update cli/sdk for Create/UpdateDetection

---

python/cli/prelude_cli/views/detect.py

```
(venv) mahinakaholokula@Mahinas-MacBook-Pro my-prelude % prelude detect activity --finish 2024-04-01 --tests 881f9052-fb52-4daf-9ad2-0a7ad9615baf --start 2024-04-01
[
{
"id": "c1adc735-eac3-4494-8daa-debf3e42c31e",
"date": "2024-04-01 08:30:04.857782",
"test": "881f9052-fb52-4daf-9ad2-0a7ad9615baf",
"endpoint_id": "89da5426-51df-445d-b6ca-2dc844fe12fa",
"status": 101,
"technique": "T1486",
"threat": null,
"dos": "linux-x86_64",
"control": 1,
"os": "Amazon Linux 2",
"policy": "b52c8d621529406a9ce567aa40357827"
}
]
```

CLI: add start/finish filters to activity cmd

---

python/sdk/prelude_sdk/controllers/iam_controller.py

patrick sneakysneakied his PR in before mine. this is just aligning

fix: use http session on new terms function

---

python/cli/prelude_cli/views/detect.py
python/sdk/prelude_sdk/controllers/detect_controller.py

det-1378: add technique filter to ListTests

---

python/sdk/prelude_sdk/models/codes.py

FE done: https://github.com/preludeorg/platform/pull/1803#pullrequestreview-2034559629

det-1482: update exitCode 126 name

---

shell/probe/nocturnal.sh

det-1124: nocturnal shouldn't follow redirects

---

shell/probe/raindrop.ps1

Pids were waiting forever. This may kill tests but not children of children of tests. It seems like a fair trade off. Also, some consistency fixes for var names.

DET-1578: windows probe kills tests after 45

---

python/cli/prelude_cli/views/build.py
python/sdk/prelude_sdk/controllers/build_controller.py

https://github.com/preludeorg/libraries/assets/2326140/f4bd12ea-6145-4e26-bc6a-98e35d4fddd8

DET-1537: on upload, wait for compile to complete and return compile results

---

python/sdk/prelude_sdk/models/codes.py

Expected EDR response when they encounter events - assigned per technique
BE change: https://github.com/preludeorg/service/pull/1948

det-1585: new enum for expected edr responses

---

python/cli/prelude_cli/views/partner.py
python/sdk/prelude_sdk/controllers/partner_controller.py

* `ioa-stats` does a query to CrowdStrike to collect monitor/detect/block counts per prelude detection (which can create 1-3 IOAs). Returns those counts and stores them in our BE (can be retrieved via the `partner reports` command)
* optionally can provide a specific test to query for / update
* `observed-detected` does a query to CrowdStrike to collect observed/detected counts per prelude test. Returns those counts and stores them in our BE (can be retrieved via `detect activity` commands)
* optionally can provide a specific test to query for / update
* optionally can provide how many hours into the past crwd should query for - default is "since the last time prelude queried crwd"
```
(venv) mahinakaholokula@Mahinas-MacBook-Pro-2 libraries % prelude --profile personal partner ioa-stats …
```

det-1726: add ioa-stats and observed-detected endpoints

---

go/tests/endpoint/endpoint.go
shell/probe/nocturnal.sh
shell/probe/raindrop.ps1
shell/probe/vision.sh

Testing:
Tested Raindrop on Win10/11
Tested nocturnal on ubuntu-23, centos9
test compiled and vscode execution on win
test compiled and go run
Incremented version of probe to 2.5
Functionality:
endpoint.go - chdir to binary dir on import - this will address `go run` issues with binary being not in .vst, and avoid issues when customer avoids Endpoint.Start()
endpoint.go - pwd uses already calculated directory (on import) instead of assessing the current binary location
raindrop.ps1 - set -WorkingDir on execution to .vst folder
nocturnal/vision - chdir to vst before execution, chdir to original folder after. 
Test Results:
```text
workingfolder testing:
Nocturnal:
Prelude probe: version 2.5
Downloading d57a4b97-6d22-48d2-afc5-8c1a98bcc8b8
Invoking d57a4b97-6d22-48d2-afc5-8c1a98bcc8b8 …
```

Det 1759 working directory

---

go/tests/endpoint/endpoint.go

In this PR:
- we adjust the filedropper slightly to streamline its functionality, optimizing for ease of use/reduced bake-in complexity
- this is done by implementing the `Dropper()` function
-- this function's purpose is to write the program bytes supplied to it (which are the dropper file), and then set the socket path so that the next write is performed using the dropper function
-- `writeIPC()` has been changed to un-set the socket path at the end of the function
-- the socket path mutator functions are now no longer exported.
- fixed cwd error variable name in Pwd

Streamlining the dropper

---

go/tests/dropper/dropper.go

In this PR:
- we publish the file dropper's source code for ease-of-build purposes!

Add dropper source code

---

go/tests/endpoint/endpoint.go

Moving @smprelude's https://github.com/preludeorg/tests/pull/343 here.

Endpoint: Adding new InsufficientPrivileges exit code and CheckAdmin()

---

python/cli/prelude_cli/views/generate.py
python/cli/prelude_cli/views/partner.py
python/sdk/prelude_sdk/controllers/build_controller.py
python/sdk/prelude_sdk/controllers/detect_controller.py
python/sdk/prelude_sdk/controllers/generate_controller.py
python/sdk/prelude_sdk/controllers/iam_controller.py
python/sdk/prelude_sdk/controllers/partner_controller.py
python/sdk/prelude_sdk/controllers/probe_controller.py
python/sdk/tests/test_build.py
python/sdk/tests/test_detect.py
python/sdk/tests/test_generate.py
python/sdk/tests/test_partner.py

added or updated:
- compile code string
- do threat hunt
- threat hunt activity
- ioa stats
- observed detected
- list partner advisories
- generate from partner advisory
- undelete test
- undelete threat
- list techniques
- partner reports
- partner block
- get test
- list tests

fix sdk tests; add new APIs (to CLI / SDK / tests)

---

shell/probe/nocturnal.sh
shell/probe/raindrop.ps1

Logging was clear in nocturnal, it was only powershell that needed to be updated.

DET-1867: Clearer logging

---

.gitignore
shell/probe/nocturnal.sh
shell/probe/raindrop.ps1
shell/probe/vision.sh

See ticket, but the nocturnal code was just broken. Tested on ubuntu arm and x86 dashes, as well as bash 3 and 4 on mac.

DET-1927 - validate nocturnal changes

---

python/sdk/tests/test_iam.py

- remove oidc from list of features in iam test

det-1950: remove oidc feature flag

---

python/cli/prelude_cli/views/build.py
python/sdk/prelude_sdk/controllers/build_controller.py
python/sdk/tests/conftest.py

- need to add control as cli arg

Det 1998 add threat hunt queries to defender

---

python/sdk/prelude_sdk/models/codes.py

next to: https://github.com/preludeorg/service/pull/2188

det-2056: add PartnerSyncJobType enum

---

python/cli/prelude_cli/views/build.py
python/cli/prelude_cli/views/detect.py
python/cli/prelude_cli/views/generate.py
python/cli/prelude_cli/views/iam.py
python/cli/prelude_cli/views/partner.py
python/cli/prelude_cli/views/shared.py

successful response example:
```
(venv) libraries % prelude detect test 07d31938-92fa-40aa-b8af-77a54055f481
{
"status": "complete",
"results": [
{
"account_id": "prelude",
"attachments": [
"07d31938-92fa-40aa-b8af-77a54055f481.go",
"07d31938-92fa-40aa-b8af-77a54055f481_darwin-arm64",
"07d31938-92fa-40aa-b8af-77a54055f481_darwin-x86_64",
"07d31938-92fa-40aa-b8af-77a54055f481_linux-arm64",
"07d31938-92fa-40aa-b8af-77a54055f481_linux-x86_64",
"07d31938-92fa-40aa-b8af-77a54055f481_windows-x86_64",
"README.md",
"redline.exe"
],
"author": "Prelude",
"created": "2023-05-11T16:55:51.403531+00:00",
"expected": {
"crowdstrike": 1
},
"id": "07d31938-92fa-40aa-b8af-77a54055f481",
"intel_context": null,
"name": "Redline Stealer",
"supported_platforms": [
"darwin",
"linux",
"windows"
],
"technique": …
```

det-2039: move to a structured json for all CLI responses

---

python/cli/prelude_cli/views/partner.py
python/sdk/prelude_sdk/controllers/partner_controller.py
python/sdk/tests/test_partner.py

examples:
get all endpoints with policy_id e09e4f0d9b2643fa8f002a401862e00c
```
prelude --profile personal partner endpoints CROWDSTRIKE --limit 5 --odata_filter "policies/any(p: p eq 'e09e4f0d9b2643fa8f002a401862e00c')"
```
get all endpoints that are in RFM
```
prelude --profile personal partner endpoints CROWDSTRIKE --limit 5 --odata_filter "reduced_functionality_mode eq true"
```
list endpoints with no edr policy attached
```
prelude --profile personal partner endpoints CROWDSTRIKE --limit 5 --odata_filter "no_edr_policy eq true"
```
list endpoints with hostname containing the word "spencer" (case insensitive)
```
prelude --profile personal partner endpoints CROWDSTRIKE --limit 5 --odata_filter "contains(tolower(hostname), 'spencer')"
```
order results by hostname desc
```
prelude …
```

det-2140: add odata params to partner endpoints

---

python/sdk/prelude_sdk/controllers/export_controller.py
python/sdk/prelude_sdk/controllers/partner_controller.py
python/sdk/tests/test_export.py
python/sdk/tests/test_generate.py
python/sdk/tests/test_partner.py
python/sdk/tests/test_policy_evaluator.py
python/sdk/tests/test_probe.py

- Add tests for export partner and get partner policy evaluations/summary

Add tests for new endpoints

---

python/sdk/prelude_sdk/controllers/partner_controller.py
python/sdk/prelude_sdk/models/codes.py
python/sdk/setup.cfg
python/sdk/tests/test_export.py
python/sdk/tests/test_iam.py

- add m365 to controls
- more test fixes

Det 2150: add m365 to controls

---

python/sdk/tests/test_build.py
python/sdk/tests/test_detect.py

- Add techniques to expected threat
- Update threat should return threat with updated techniques after https://github.com/preludeorg/service/pull/2278 is merged

Add techniques to threat sdk tests

---

python/sdk/prelude_sdk/models/codes.py
python/sdk/setup.cfg

Blocks https://github.com/preludeorg/service/pull/2271

det-2208/support_role

---

python/sdk/tests/test_policy_evaluator.py

- already being updated on partner attach

Skip update test if existing job

---

python/sdk/prelude_sdk/models/codes.py
python/sdk/setup.cfg

intentionally leaving the SIEMs out for now

det-2211: add mappings from control to category

---

python/cli/prelude_cli/views/scm.py
python/cli/setup.cfg
python/sdk/prelude_sdk/controllers/scm_controller.py
python/sdk/setup.cfg
python/sdk/tests/test_scm.py

* add list users & list inboxes
* add odata filters to eval and eval summary
* fix tests

det-2342: update CLI - more SCM stuff

---

python/cli/setup.cfg

so we can release fix in https://github.com/preludeorg/libraries/pull/1134

det-2245: bump cli version

---

python/cli/prelude_cli/views/detect.py
python/cli/prelude_cli/views/scm.py
python/sdk/prelude_sdk/controllers/detect_controller.py
python/sdk/prelude_sdk/controllers/export_controller.py
python/sdk/prelude_sdk/controllers/scm_controller.py
python/sdk/tests/test_scm.py
python/sdk/tests/test_scm_build.py

it's not all the new stuff, but it's some of it :)

det-2342: async jobs and scm exceptions in sdk/cli/tests

---

python/cli/prelude_cli/cli.py
python/cli/prelude_cli/views/detect.py
python/cli/prelude_cli/views/jobs.py
python/cli/prelude_cli/views/partner.py
python/cli/prelude_cli/views/scm.py
python/sdk/prelude_sdk/controllers/detect_controller.py
python/sdk/prelude_sdk/controllers/jobs_controller.py
python/sdk/prelude_sdk/controllers/partner_controller.py
python/sdk/tests/test_scm.py

- Job statuses route moved to /jobs/statuses
- Update evaluation SDK test needs to wait until background job completes

Det-2389: jobs controller

---

python/cli/prelude_cli/views/partner.py
python/cli/prelude_cli/views/scm.py
python/sdk/prelude_sdk/controllers/export_controller.py
python/sdk/prelude_sdk/controllers/partner_controller.py
python/sdk/prelude_sdk/controllers/scm_controller.py
python/sdk/tests/conftest.py
python/sdk/tests/test_partner.py
python/sdk/tests/test_scm.py

tacked on to https://github.com/preludeorg/service/pull/2419

det-2440: cli / sdk changes for multiple instances per control

---

python/cli/prelude_cli/views/scm.py
python/cli/setup.cfg
python/sdk/prelude_sdk/controllers/scm_controller.py
python/sdk/setup.cfg

Update the CLI / SDK for more ux consistency between detect and scm.

DET-2511: scm threats all the fields

---

python/cli/prelude_cli/views/build.py
python/cli/setup.cfg
python/sdk/prelude_sdk/controllers/build_controller.py
python/sdk/setup.cfg

Seems to work. Maybe could use some unit tests.

det-2563/test_compile_tests_with_embeds

---

python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py
python/sdk/prelude_sdk/models/account.py

- tested with non-migrated keychain file, running any CLI command/sdk function migrates good profiles and skips bad profiles

Det 2529: force migration

---

python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py
python/sdk/tests/conftest.py
python/sdk/tests/test_iam.py

- CLI and SDK functions for forgot password/change password

Det 2731 user reset

---

python/sdk/tests/conftest.py
python/sdk/tests/test_iam.py

which doesnt get 'temp_password' back in response

fix up sdk tests for prod

---

python/sdk/prelude_sdk/models/codes.py
python/sdk/setup.cfg

service now will move over in a different PR so I dont break us2 in the meantime

det-2749: add discovered_devices control category

---

python/cli/prelude_cli/views/iam.py
python/sdk/prelude_sdk/controllers/iam_controller.py
python/sdk/tests/test_iam.py

- tested in personal env
```
prelude --profile tanya iam user change-password
Current password: 
New password: 
{
"status": "complete",
"results": [
{
"status": true
}
],
"message": "Password changed successfully"
}
```

Det 2762: change password

---

python/cli/setup.cfg
python/sdk/prelude_sdk/models/codes.py
python/sdk/setup.cfg

azure devops in fact does not work haha

det-2881: backout AZURE_DEVOPS, update sdk/cli versions

---

python/sdk/tests/test_scm.py

fix sdk tests before release

---

python/sdk/prelude_sdk/controllers/scm_controller.py

adding to sdk so we can test. dont think there's a reason to add to CLI since this is for a UI nicety

det-2930: add saved views to sdk

---

python/sdk/tests/conftest.py
python/sdk/tests/test_build.py

det-3067: sdk test thrunt. for real this time

---

python/cli/prelude_cli/views/scm.py
python/sdk/prelude_sdk/controllers/scm_controller.py

- sdk/cli for https://github.com/preludeorg/service/pull/2790

Det 3156: history

---

python/cli/prelude_cli/views/scm.py
python/cli/setup.cfg
python/sdk/prelude_sdk/controllers/scm_controller.py

don't see it used in sdk tests

det-3152: update sdk/cli re: policy exceptions CRUD api

---

.github/CODEOWNERS

Remove Keith from codeowners

---

python/cli/prelude_cli/views/scm.py
python/sdk/prelude_sdk/controllers/scm_controller.py

w/ https://github.com/preludeorg/service/pull/2841

det-3272: policy_type flags for scm

---

python/cli/prelude_cli/views/scm.py
python/sdk/prelude_sdk/controllers/scm_controller.py

- separate this out so the other one can get deployed first

Det 3227: sdk/cli

---

python/sdk/prelude_sdk/models/codes.py
python/sdk/setup.cfg

Right now, we don't have any recommendations for MFA policy types for okta / entra, so gonna remove card

det-3516: add policy type <> control mappings
